DROP PUBLICATION IF EXISTS supabase_realtime;

CREATE PUBLICATION supabase_realtime;

ALTER PUBLICATION supabase_realtime ADD TABLE 
"User",
"Organization",
"ApiKey",
"OrganizationMember",
"GoogleConnection",
"Source",
"SourceRule",
"SourceRun",
"Email",
"EmailAttachment",
"EmailLink",
"Document",
"DocumentChunk",
"Schema",
"SchemaField",
"Dataset",
"DatasetRecord",
"DatasetValue",
"AiJob",
"AiOutput",
"SharingRequest",
"SharingPermission",
"AuditLog",
"UsageMetric",
"Webhook",
"CrossOrgPermission",
"DatasetAccess",
"Invitation",
"AgentLog",
"GoogleSheetsAccount",
"SpreadsheetConnection",
"SheetMapping",
"DatasetSchemaVersion",
"DatasetColumnDef",
"DatasetRowExternalId",
"SyncState",
"SyncEvent",
"SyncConflict",
"ImportJob",
"ImportMapping",
"Invoice",
"AssistantSession",
"AssistantMessage";
