/**
 * POST /api/assistant/undo
 *
 * Reverses a previously confirmed write action using an undo token.
 *
 * Undo tokens are short-lived (1-hour TTL), stateless base64-JSON blobs
 * generated by the /confirm route. This route decodes the token, validates
 * its expiry and org ownership, then performs the reverse operation.
 *
 * Supported undo operations:
 *   delete_schema       → deletes the schema that was AI-created
 *   delete_dataset      → deletes the dataset that was AI-created
 *   recreate_schema     → re-creates a schema from the before-state snapshot
 *   delete_schema_field → removes a field that was AI-added
 *   restore_member_role → restores a member's previous role
 *   resume_source       → resumes a source that was AI-paused
 *   pause_source        → pauses a source that was AI-resumed
 *
 * All undo actions are logged to the audit log with actorType="ai".
 *
 * Request body:
 *   { undoToken: string }
 *
 * Response:
 *   { ok: true, message: string }
 */

import { NextRequest, NextResponse } from "next/server";
import { requireRole, AuthError, authErrorResponse } from "@/lib/auth";
import { db } from "@/lib/db";
import { logAudit } from "@/lib/audit";
import { decryptContent } from "../crypto";

// ── Token type ────────────────────────────────────────────────────────────

interface UndoPayload {
  action:
    | "delete_schema"
    | "delete_dataset"
    | "recreate_schema"
    | "delete_schema_field"
    | "restore_member_role"
    | "resume_source"
    | "pause_source";
  entity: string;
  entityId?: string;
  /** Used by restore_member_role */
  email?: string;
  before?: {
    /** recreate_schema */
    name?: string;
    description?: string | null;
    /** recreate_schema_field */
    type?: string;
    required?: boolean;
    position?: number;
    options?: any;
    promptTemplate?: string | null;
    fields?: Array<{
      name: string; type: string; description?: string | null;
      instructions?: string | null; required: boolean; options?: string | null; position: number;
    }>;
    /** restore_member_role */
    role?: string;
  };
  expiresAt: number; // unix ms
}

// ── Route handler ─────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const { user, organizationId } = await requireRole(req, "member");
    const body = await req.json().catch(() => ({}));
    const rawToken = body.undoToken;

    if (!rawToken || typeof rawToken !== "string") {
      return NextResponse.json({ error: "Missing undoToken" }, { status: 400 });
    }

    // Decode and validate the undo token
    let payload: UndoPayload;
    try {
      payload = JSON.parse(decryptContent(rawToken)) as UndoPayload;
    } catch {
      return NextResponse.json({ error: "Invalid or forged undo token" }, { status: 400 });
    }

    // TTL check — tokens expire after 1 hour
    if (Date.now() > payload.expiresAt) {
      return NextResponse.json(
        { error: "Undo token has expired. This action can no longer be reversed." },
        { status: 410 }
      );
    }

    switch (payload.action) {

      // ── Undo: create_schema — delete what was created ───────────────────
      case "delete_schema": {
        const schema = await db.schema.findFirst({
          where: { id: payload.entityId!, organizationId },
        });
        if (!schema) {
          return NextResponse.json(
            { error: "Schema not found — it may have already been deleted" },
            { status: 404 }
          );
        }
        await db.schema.delete({ where: { id: payload.entityId! } });
        await logAudit({
          organizationId, actorId: user.id, actorType: "ai",
          action: "undo_create", entity: "schema", entityId: payload.entityId,
          reason: "User undid AI-created schema",
        });
        return NextResponse.json({ ok: true, message: `Schema "${schema.name}" has been removed.` });
      }

      // ── Undo: create_dataset — delete what was created ──────────────────
      case "delete_dataset": {
        const dataset = await db.dataset.findFirst({
          where: { id: payload.entityId!, organizationId },
        });
        if (!dataset) {
          return NextResponse.json(
            { error: "Dataset not found — it may have already been deleted" },
            { status: 404 }
          );
        }
        await db.dataset.delete({ where: { id: payload.entityId! } });
        await logAudit({
          organizationId, actorId: user.id, actorType: "ai",
          action: "undo_create", entity: "dataset", entityId: payload.entityId,
          reason: "User undid AI-created dataset",
        });
        return NextResponse.json({ ok: true, message: `Dataset "${dataset.name}" has been removed.` });
      }

      // ── Undo: delete_schema — re-create from before-state snapshot ───────
      case "recreate_schema": {
        if (!payload.before?.name) {
          return NextResponse.json(
            { error: "Undo data is missing — cannot recreate schema" },
            { status: 400 }
          );
        }
        const { name, description, promptTemplate, fields = [] } = payload.before;
        const recreated = await db.$transaction(async (tx) => {
          const schema = await tx.schema.create({
            data: {
              organizationId, createdBy: user.id,
              name, description: description ?? null,
              promptTemplate: promptTemplate ?? null,
              version: 1,
            },
          });
          if (fields.length > 0) {
            await tx.schemaField.createMany({
              data: fields.map((f) => ({
                schemaId: schema.id,
                name: f.name, type: f.type,
                description: f.description ?? null,
                instructions: f.instructions ?? null,
                required: f.required,
                options: f.options ?? null,
                position: f.position,
              })),
            });
          }
          return schema;
        });
        await logAudit({
          organizationId, actorId: user.id, actorType: "ai",
          action: "undo_delete", entity: "schema", entityId: recreated.id,
          reason: `Recreated schema "${name}" after AI deletion`,
        });
        return NextResponse.json({
          ok: true,
          message: `Schema "${name}" has been restored with ${fields.length} field(s).`,
        });
      }

      // ── Undo: add_schema_field — remove the field that was added ─────────
      case "delete_schema_field": {
        const field = await db.schemaField.findFirst({ where: { id: payload.entityId! } });
        if (!field) {
          return NextResponse.json(
            { error: "Field not found — it may have already been removed" },
            { status: 404 }
          );
        }
        // Verify org ownership via the parent schema
        const schema = await db.schema.findFirst({ where: { id: field.schemaId, organizationId } });
        if (!schema) {
          return NextResponse.json({ error: "Access denied" }, { status: 403 });
        }
        await db.schemaField.delete({ where: { id: payload.entityId! } });
        await db.schema.update({ where: { id: field.schemaId }, data: { version: schema.version + 1 } });
        await logAudit({
          organizationId, actorId: user.id, actorType: "ai",
          action: "undo_add_field", entity: "schema_field", entityId: payload.entityId,
          reason: `Removed field "${field.name}" that AI added`,
        });
        return NextResponse.json({
          ok: true,
          message: `Field "${field.name}" has been removed from schema "${schema.name}".`,
        });
      }

      // ── Undo: update_member_role — restore previous role ─────────────────
      case "restore_member_role": {
        const previousRole = payload.before?.role;
        const targetEmail = payload.email;
        if (!previousRole || !targetEmail) {
          return NextResponse.json({ error: "Undo data incomplete" }, { status: 400 });
        }
        
        // Security Check: Enforce role hierarchy for AI-driven undo role changes
        const ROLE_LEVEL: Record<string, number> = { owner: 5, admin: 4, manager: 3, member: 2, viewer: 1 };
        const actorMembership = await db.organizationMember.findUnique({
          where: { organizationId_userId: { organizationId, userId: user.id } }
        });
        if (!actorMembership || actorMembership.status !== "active") return NextResponse.json({ error: "Access denied" }, { status: 403 });
        const actorLevel = ROLE_LEVEL[actorMembership.role] ?? 0;
        if (actorLevel < ROLE_LEVEL.manager) return NextResponse.json({ error: "Only managers and above can restore roles." }, { status: 403 });

        const targetUser = await db.user.findUnique({ where: { email: targetEmail } });
        if (!targetUser) {
          return NextResponse.json({ error: `User "${targetEmail}" not found` }, { status: 404 });
        }
        const membership = await db.organizationMember.findFirst({
          where: { organizationId, userId: targetUser.id, status: "active" },
        });
        if (!membership) {
          return NextResponse.json({ error: `"${targetEmail}" is no longer a member` }, { status: 404 });
        }

        const targetLevel = ROLE_LEVEL[membership.role] ?? 0;
        const newLevel = ROLE_LEVEL[previousRole] ?? 0;

        if (user.id === targetUser.id) {
          if (newLevel > targetLevel) return NextResponse.json({ error: "You cannot promote yourself." }, { status: 403 });
        } else {
          if (actorLevel <= targetLevel && membership.role !== "viewer") return NextResponse.json({ error: `You cannot modify the role of a ${membership.role}` }, { status: 403 });
          if (actorLevel < newLevel) return NextResponse.json({ error: `You cannot grant a role higher than your own` }, { status: 403 });
        }

        await db.organizationMember.update({ where: { id: membership.id }, data: { role: previousRole } });
        await logAudit({
          organizationId, actorId: user.id, actorType: "ai",
          action: "undo_role_change", entity: "org_member", entityId: membership.id,
          reason: `Restored ${targetEmail} role to ${previousRole}`,
        });
        return NextResponse.json({
          ok: true,
          message: `${targetEmail}'s role has been restored to "${previousRole}".`,
        });
      }

      // ── Undo: pause_source — resume the source ───────────────────────────
      case "resume_source": {
        const source = await db.source.findFirst({ where: { id: payload.entityId!, organizationId } });
        if (!source) return NextResponse.json({ error: "Source not found" }, { status: 404 });
        await db.source.update({ where: { id: payload.entityId! }, data: { status: "active" } });
        await logAudit({
          organizationId, actorId: user.id, actorType: "ai",
          action: "undo_pause", entity: "source", entityId: payload.entityId,
        });
        return NextResponse.json({ ok: true, message: `Source "${source.name}" has been resumed.` });
      }

      // ── Undo: resume_source — pause the source ───────────────────────────
      case "pause_source": {
        const source = await db.source.findFirst({ where: { id: payload.entityId!, organizationId } });
        if (!source) return NextResponse.json({ error: "Source not found" }, { status: 404 });
        await db.source.update({ where: { id: payload.entityId! }, data: { status: "paused" } });
        await logAudit({
          organizationId, actorId: user.id, actorType: "ai",
          action: "undo_resume", entity: "source", entityId: payload.entityId,
        });
        return NextResponse.json({ ok: true, message: `Source "${source.name}" has been paused.` });
      }

      default:
        return NextResponse.json({ error: "Unsupported undo action" }, { status: 400 });
    }
  } catch (err) {
    if (err instanceof AuthError) return authErrorResponse(err);
    console.error("[assistant/undo] error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Undo failed" },
      { status: 500 }
    );
  }
}
