import { PublicHeader } from "@/components/public/public-header";
import { PublicFooter } from "@/components/public/public-footer";

export const metadata = {
  title: "Privacy Policy | Workspace Intelligence Platform",
};

export default function PrivacyPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <PublicHeader />
      <main className="flex-1 py-16 md:py-24">
        <div className="mx-auto max-w-3xl px-4 md:px-6">
          <h1 className="text-4xl font-bold tracking-tight mb-4">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground mb-12">Last Updated: August 26, 2026</p>

          <div className="space-y-8 text-muted-foreground leading-relaxed">
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">1. Introduction</h2>
              <p>
                Workspace Intelligence Platform ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our SaaS application to extract and manage data from your Google Workspace environment.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">2. Data We Collect</h2>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li><strong>Account Information:</strong> We collect your email address and authentication credentials securely via Supabase Auth when you sign up.</li>
                <li><strong>Google Workspace Data:</strong> When you connect your Google Account via OAuth, we access data based on the explicit scopes you grant (e.g., read-only access to Gmail or Google Drive). We only fetch data that matches the specific ingestion rules you configure.</li>
                <li><strong>Extracted Data:</strong> The structured datasets generated by our AI from your unstructured documents are stored in our secure PostgreSQL database.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">3. How We Use Your Data</h2>
              <p>
                Your data is strictly used to provide the Workspace Intelligence Platform service. Specifically:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>To ingest and parse your selected emails and documents.</li>
                <li>To process unstructured text through large language models (LLMs) to extract structured fields.</li>
                <li>To provide you with a dashboard to view, query, and export your extracted datasets.</li>
              </ul>
              <p className="mt-4 font-medium text-foreground">Zero-Training Policy for AI</p>
              <p>
                We do not use your personal data, Google Workspace data, or extracted datasets to train, fine-tune, or improve our base AI models, nor do we allow third-party LLM providers (e.g., Google Gemini) to retain your data for model training purposes. Data sent to LLMs is used strictly for immediate inference.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">4. Data Storage and Security</h2>
              <p>
                We employ enterprise-grade security measures to protect your data:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li><strong>OAuth Tokens:</strong> Encrypted at rest using strict key rotation policies.</li>
                <li><strong>Database Security:</strong> All extracted data and metadata are stored in Supabase PostgreSQL databases with strict Row-Level Security (RLS) policies enforcing tenant isolation by Organization ID.</li>
                <li><strong>Transit:</strong> All data in transit is encrypted using TLS 1.3.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">5. Data Retention and Deletion</h2>
              <p>
                We retain your extracted datasets and audit logs as long as your account is active, or in accordance with your chosen subscription tier (e.g., 7-day, 90-day, or unlimited retention). You may delete datasets, disconnect your Google account, or delete your entire organization at any time, which will permanently remove the associated data from our active databases.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">6. Contact Us</h2>
              <p>
                If you have questions or comments about this Privacy Policy, please contact us via the <a href="/contact" className="text-primary hover:underline">Contact page</a> or email us at privacy@example.com.
              </p>
            </section>

          </div>
        </div>
      </main>
      <PublicFooter />
    </div>
  );
}
